CREATE TABLE ADDRESS (
ADDRESSID VARCHAR(256) NOT NULL,
STREET VARCHAR(256) ,
STATE VARCHAR(256) ,
ZIP VARCHAR(256) ,
CITY VARCHAR(256) ,
CONSTRAINT PK_ADDRESS PRIMARY KEY (ADDRESSID)
)
;
CREATE TABLE CUSTOMER (
FIRSTNAME VARCHAR(256) ,
CUSTOMERID VARCHAR(256) NOT NULL,
LASTNAME VARCHAR(256) ,
CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMERID)
)
;
CREATE TABLE SUBSCRIPTION (
TYPE VARCHAR(256) ,
TITLE VARCHAR(256) NOT NULL,
CONSTRAINT PK_SUBSCRIPTION PRIMARY KEY (TITLE)
)
;
CREATE TABLE CUSTOMERBEANSUBSCRIPTIONBEAN (
CUSTOMERBEAN_CUSTOMERID96 VARCHAR(256) ,
SUBSCRIPTIONBEAN_TITLE VARCHAR(256) 
)
;
CREATE TABLE CUSTOMER_ADDRESS(
CUSTOMER_CUSTOMERID VARCHAR(256) ,
ADDRESSES_ADDRESSID VARCHAR(256) 
)
;

ALTER TABLE CUSTOMERBEANSUBSCRIPTIONBEAN ADD CONSTRAINT FK_SUBSCRIPTIONS FOREIGN KEY (CUSTOMERBEAN_CUSTOMERID96) REFERENCES CUSTOMER (CUSTOMERID)
;
ALTER TABLE CUSTOMERBEANSUBSCRIPTIONBEAN ADD CONSTRAINT FK_CUSTOMERS FOREIGN KEY (SUBSCRIPTIONBEAN_TITLE) REFERENCES SUBSCRIPTION (TITLE)
;
ALTER TABLE CUSTOMER_ADDRESS ADD CONSTRAINT FK_CUSTOMER_ADDRESS_ADDRESS FOREIGN KEY (ADDRESSES_ADDRESSID) REFERENCES ADDRESS (ADDRESSID)
;
ALTER TABLE CUSTOMER_ADDRESS ADD CONSTRAINT FK_CUSTOMER_ADDRESS_CUSTOMER FOREIGN KEY (CUSTOMER_CUSTOMERID) REFERENCES CUSTOMER (CUSTOMERID)
;